# Docker {#sec-docker}


## Instalación de Docker Desktop

[Docker Desktop](https://docs.docker.com/desktop/) es una aplicación que combina varias
herramientas para crear, compartir y ejecutar contenedores virtuales de aplicaciones y 
microservicios.

Incluye la herramienta [Docker Compose](https://docs.docker.com/compose/), que permite
definir y ejecutar applicaciones que necesitan múltiples contendores virtuales
interconectados.

Para instalar Docker Desktop en nuestro equipo o máquina virtual de Linux, se recomienda
seguir las [instrucciones de instalación usando el repositorio APT oficial](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository).

Una vez agregado el repositorio y las claves de autenticación a nuestro sistema, se instalan
los paquetes necesarios con el comando:

```bash
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

## Descarga y ejecución de imágenes


## Gestión de aplicaciones con múltiples contenedores


## Archivos de configuración